imports:
  - { resource: config.yml }

framework:
  router:
    resource: '%kernel.project_dir%/resources/config/routing_development.yml'
  profiler: ~

web_profiler:
  toolbar: true

oneup_flysystem:
  adapters:
    uploads:
      local:
        directory: "%kernel.root_dir%/../web/uploads"

  filesystems:
    uploads:
      adapter: uploads
      alias: upload_filesystem

doctrine:
  dbal:
    url: mysql://%database.user%:%database.password%@%database.host%/%database.database%
    default_table_options:
      charset: utf8mb4
      collate: utf8mb4_unicode_ci
  orm:
    auto_mapping: true
    auto_generate_proxy_classes: true
    mappings:
      OpenCFP\Domain\Entity:
        type: annotation
        dir: "%kernel.root_dir%/../src/Domain/Entity"
        prefix: OpenCFP\Domain\Entity

