services:
  _defaults:
    public: false
    autowire: true

  GuzzleHttp\ClientInterface:
    class: GuzzleHttp\Client

  OpenCFP\Http\Controller\:
    resource: '%kernel.project_dir%/src/Http/Controller/*'
    public: true
    bind:
      $applicationAirport: '%application.airport%'
      $applicationArrival: '%application.arrival%'
      $applicationDeparture: '%application.departure%'

  OpenCFP\Http\Action\:
    resource: '%kernel.project_dir%/src/Http/Action/*'
    public: true
    bind:
      $applicationEmail: '%application.email%'
      $applicationEndDate: '%application.enddate%'
      $applicationTitle: '%application.title%'
      $forgotForm: '@OpenCFP\Http\Form\ForgotForm'
      $resetForm: '@OpenCFP\Http\Form\ResetForm'
      $showSubmissionCount: '%application.show_submission_count%'

  OpenCFP\Http\Action\Security\SsoAction:
    public: true
    bind:
      $clientId: '%opencfpcentral.clientId%'
      $redirectUri: '%opencfpcentral.redirectUri%'
      $authorizeUrl: '%opencfpcentral.authorizeUrl%'

  OpenCFP\Http\Action\Security\SsoRedirectAction:
    public: true
    bind:
      $clientId: '%opencfpcentral.clientId%'
      $clientSecret: '%opencfpcentral.clientSecret%'
      $redirectUri: '%opencfpcentral.redirectUri%'
      $resourceUri: '%opencfpcentral.resourceUri%'
      $tokenUrl: '%opencfpcentral.tokenUrl%'

  OpenCFP\Http\Action\Security\ShowLogInAction:
    public: true
    bind:
      $sso: '%opencfpcentral.sso%'

  OpenCFP\Http\Form\ForgotForm:
    class: Symfony\Component\Form\FormInterface
    factory: [OpenCFP\Http\Form\FormFactory, create]
    bind:
      $formType: OpenCFP\Http\Form\ForgotFormType

  OpenCFP\Http\Form\ResetForm:
    class: Symfony\Component\Form\FormInterface
    factory: [OpenCFP\Http\Form\FormFactory, create]
    bind:
      $formType: OpenCFP\Http\Form\ResetFormType

  OpenCFP\Http\View\TalkHelper:
    arguments:
      - '%talk.categories%'
      - '%talk.levels%'
      - '%talk.types%'

  OpenCFP\PathInterface:
    class: OpenCFP\Path
    bind:
      $path: '%kernel.project_dir%'

  OpenCFP\WebPath:
      class: OpenCFP\WebPath

  OpenCFP\Application\Speakers: ~

  OpenCFP\Environment:
    autowire: false
    factory: [OpenCFP\Environment, fromString]
    arguments: ['%kernel.environment%']

  Swift_Mailer:
    public: true
    class: Swift_Mailer

