version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2-fpm-node-browsers
      - image: tkuchiki/delayed-mysql
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: cfp_test

    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install mysql-client
      - run: sudo docker-php-ext-install pdo_mysql
      - run: sudo composer self-update
      - run: composer validate --no-check-publish
      - run: composer install
      - run: vendor/bin/php-cs-fixer fix --config=.php_cs.dist --dry-run --diff -v --using-cache=no
      - run: cp config/testing.yml.dist config/testing.yml
      - run: CFP_ENV=testing vendor/bin/phinx migrate --environment testing
      - run: yarn install
      - run: yarn run production
      - run: SYMFONY_DEPRECATIONS_HELPER=disabled vendor/bin/phpunit --testsuite auto-review
      - run: SYMFONY_DEPRECATIONS_HELPER=disabled vendor/bin/phpunit --testsuite integration
      - run: SYMFONY_DEPRECATIONS_HELPER=disabled vendor/bin/phpunit --testsuite unit
